# Generated by Django 5.0.6 on 2024-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('map_location', models.URLField()),
                ('availability', models.BooleanField(default=True)),
                ('safety', models.TextField()),
                ('weather', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('speciality', models.TextField()),
                ('city_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thumbnail_picture', models.URLField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_6_months', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_1_year', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rent_individual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('groceries_individual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('others_individual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_individual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_family', models.DecimalField(decimal_places=2, max_digits=10)),
                ('groceries_family', models.DecimalField(decimal_places=2, max_digits=10)),
                ('others_family', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_family', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pictures', models.JSONField(default=list)),
            ],
        ),
    ]
