# Generated by Django 5.0.6 on 2024-06-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostadvertisements', '0003_advertisement_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='host',
            new_name='user_id',
        ),
    ]
