# Generated by Django 5.0.6 on 2024-06-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostadvertisements', '0006_advertisement_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='comments',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
