# Generated by Django 5.0.6 on 2024-06-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_stripe_charge_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_charge_id',
        ),
    ]
