# Generated by Django 5.0.6 on 2024-06-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_transaction_stripe_charge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='stripe_payment_intent_id',
        ),
    ]
