# Generated by Django 5.0.6 on 2024-06-21 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_from_date_booking_number_of_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='to_date',
            field=models.DateField(default=datetime.date(2024, 6, 23)),
        ),
    ]
